// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

@ffi.Native<
  ffi.Pointer<pixels_t> Function(
    ffi.Uint32,
    ffi.Uint32,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Double>,
    ffi.Pointer<ffi.Uint32>,
    ffi.Size,
  )
>()
external ffi.Pointer<pixels_t> calculate_voronoi_fortune(
  int width,
  int height,
  ffi.Pointer<ffi.Double> points_x,
  ffi.Pointer<ffi.Double> points_y,
  ffi.Pointer<ffi.Uint32> point_colors,
  int points_count,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<pixels_t>)>()
external void free_pixels(ffi.Pointer<pixels_t> pixels);

final class pixels_t extends ffi.Struct {
  external ffi.Pointer<ffi.Uint32> colors;

  @ffi.Size()
  external int size;
}
